### ISSUE TITLE
Still not working

### ISSUE THREAD

**Issue by MTLPGaming** [nachomonkey/RefreshAllNodes#2]
Hi, it's me again.

I just tried your new file but it still throws up an error that the Plugin may be compiled for a different Unreal Engine Version...
![ScreenShot_20210418121611](https://user-images.githubusercontent.com/82660680/115142042-df059180-a03f-11eb-8d56-1785ec4d04df.png)

**Comment by nachomonkey** [comment]
The plugin is written in C++ and must be compiled before you can use it, so it's not really an error; it's just saying it hasn't been compiled. I think the problem is that you don't have anything installed that can compile the plugin.

Start with installing Visual Studio and following these steps:

https://docs.unrealengine.com/en-US/ProductionPipelines/DevelopmentSetup/VisualStudioSetup/index.html

After installing VS, try opening up your project like before. You will probably get a similar message, but there should be a button to let you compile it.

I hope this helps, please follow up if you have any problems.

**Comment by MTLPGaming** [comment]
Ok, i tried it a few times now and it just keeps giving me the same error...

**Comment by nachomonkey** [comment]
Okay, this should solve it.
I have uploaded pre-compiled binaries of the plugin for Unreal Engine 4.26.2 on Win64, so you do not have to compile it yourself.

Here is what you need to do:

* Delete the plugin from your computer
* Download and extract [the release](https://github.com/nachomonkey/RefreshAllNodes/archive/refs/tags/v1.1-UE4.26.2.zip) into your project's Plugins directory
* Launch the editor and see if it works.

Note: Whenever you update Unreal Engine, you will need to repeat this process with a new release of the plugin that matches your Unreal Engine version. Find the releases here:

https://github.com/nachomonkey/RefreshAllNodes/releases

**Comment by MTLPGaming** [comment]
Ok, it still doesn't work.I don't know why, but i get the same error again...

Can you tell me how i can compile it myself? then i would just change some random values and try it over and over and over.

I'm sure that the Problem lies on my side in a way. I just needed the plugin to try to fix my UE4 Project. I'm sorry for any time you wasted on me, I'm sure that you do great work.

**Comment by MTLPGaming** [comment]
Nevermind, i did something and it worked!

Thanks for your Help!!!!
